name: Deploy to production

concurrency: production

on:
  workflow_dispatch:

jobs:
  rollback:
    environment: production
    concurrency: production
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy to production
        env:
          SSHPASS: ${{ secrets.BLOG_PROD_SECRET }}
        run: |
          sshpass -e ssh ${{ secrets.BLOG_PROD_USER }}@sewera.dev './DEPLOY_BLOG'
